# dummy change to force redeploy
backend:
  name: github
  repo: KF-Media/landing
  branch: main
  client_id: Ov23liPIgewKff5gLn8Q

media_folder: "Asset/uploads"
public_folder: "/Asset/uploads"

publish_mode: editorial_workflow

collections:
  - name: "hero"
    label: "Hero Section"
    folder: "content/hero"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Subjudul", name: "subtitle", widget: "string" }
      - { label: "CTA Button Text", name: "cta_text", widget: "string" }

  - name: "services"
    label: "Layanan"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama layanan", name: "name", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - { label: "Harga estimasi", name: "price_estimate", widget: "string" }
      - label: "Badge"
        name: "badge"
        widget: "select"
        options:
          - "Populer"
          - "Hemat"
        required: false

  - name: "portfolio"
    label: "Portofolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul proyek", name: "project_title", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - label: "Gambar"
        name: "image"
        widget: "image"
        required: true
      - { label: "Link", name: "link", widget: "string" }

  - name: "testimonials"
    label: "Testimoni"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama klien", name: "client_name", widget: "string" }
      - { label: "Kutipan singkat", name: "quote", widget: "text" }

  - name: "contact"
    label: "Kontak"
    folder: "content/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nomor WhatsApp", name: "whatsapp", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - label: "Sosial Media"
        name: "social_media"
        widget: "list"
        fields:
          - { label: "Platform", name: "platform", widget: "string" }
          - { label: "Link", name: "link", widget: "string" }
